title: Margaret O'Connor 
logo: "crop.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  ðŸ’» Excel, SQL, Tableau, Python, R, Bash
  <br>
  I'm a ðŸ§¬ Molecular Biologist interested in ðŸ“Š Data Analytics and Bioinformatics.
  <br>
  When I'm not working, I enjoy crafts like ðŸ§¶crochet and ðŸª¡cross stitch.
  <br>
  Explore my data analytics projects here or find me on LinkedIn!  <br><br>
  <a href="https://www.linkedin.com/in/margaret-o-connor-ph-d-1051b155/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
